# Generated by Django 5.2.9 on 2026-02-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_app', '0002_comment_text_en_comment_text_ru_post_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='like',
            field=models.BooleanField(),
        ),
    ]
