# Generated by Django 5.2.9 on 2026-02-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_app', '0003_alter_commentlike_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
    ]
